services:
  stats-server:
    build: stat-service/server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:16.1
    container_name: stat-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=stat-db

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_SERVER_URL=http://server:9090

  ewm-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=main-db